name: Issue SSL certificate
on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

env:
  Ali_Key: ${{ secrets.ALI_KEY }}
  Ali_Secret: ${{ secrets.ALI_SECRET }}

jobs:
  issue-docs-ssl-certificate:
    name: Issue Docs SSL certificate
    runs-on: ubuntu-latest
    steps:
      - uses: Menci/acme@v2
        with:
          version: 3.0.2
          domains: docs.terraria.ink
          append-wildcard: false

          arguments: --server letsencrypt --dns dns_ali
          arguments-file: ''

          output-cert: output/cert.pem
          output-fullchain: output/fullchain.pem
          output-key: output/key.pem
   
      - uses: Menci/deploy-certificate-to-aliyun@beta-v1
        with:
    
          access-key-id: ${{ secrets.ALI_KEY }}
          access-key-secret: ${{ secrets.ALI_SECRET }}
          
          fullchain-file: output/fullchain.pem
          key-file: output/key.pem

          certificate-name: TShockPluginsDocs

          # (Optional) Deploy to CDN
          cdn-domains: |
            docs.terraria.ink
        
          # (Optional) API request timeout (unit ms)
          timeout: 10000

          # (Optional) API request attempt times
          retry: 3
          
  issue-ssl-certificate:
    name: Issue CaiBotRaw SSL certificate
    runs-on: ubuntu-latest
    steps:
      - uses: Menci/acme@v2
        with:
          version: 3.0.2
          domains: raw.terraria.ink
          append-wildcard: false
  
          arguments: --server letsencrypt --dns dns_ali
          arguments-file: ''
  
          output-cert: output/cert.pem
          output-fullchain: output/fullchain.pem
          output-key: output/key.pem
   
      - uses: Menci/deploy-certificate-to-aliyun@beta-v1
        with:
    
          access-key-id: ${{ secrets.ALI_KEY }}
          access-key-secret: ${{ secrets.ALI_SECRET }}
          
          fullchain-file: output/fullchain.pem
          key-file: output/key.pem
  
          certificate-name: CaiBotApi
  
          # (Optional) Deploy to CDN
          cdn-domains: |
            raw.terraria.ink
        
          # (Optional) API request timeout (unit ms)
          timeout: 10000
  
          # (Optional) API request attempt times
          retry: 3
  
